name: Deploy Angular App
on:
  push:
    branches:
      - 'main'
      - 'prod'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint Application
        run: npm run lint
  build:
    needs: lint
    continue-on-error: true
    runs-on: self-hosted
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-files
          path: dist
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Get build Project
        uses: actions/download-artifact@v3
        with:
          name: build-files
      - name: Display structure of downloaded files
        run: ls -R
