name: Deploy Angular App
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Deploy Application
        run: npm run build
