name: Deploy Angular App
on:
  push:
    branches:
      - 'prod'
    # paths-ignore:
    #   - '.github/workflows/*'
jobs:
  lint:
    runs-on: [self-hosted, Linux, X64]
    steps:
      -
        name: Get repository code
        uses: actions/checkout@v3
      -
        name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      -
        name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      -
        name: Install Dependencies
        run: npm ci
      -
        name: Lint Application
        run: npm run lint
  build:
    needs: lint
    # continue-on-error: true
    runs-on: [self-hosted, Linux, X64]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: victorvsm/angular-themes-switcher:latest
  deploy:
    needs: build
    runs-on: [self-hosted, Linux, X64]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Run image
        run: |
          docker pull victorvsm/angular-themes-switcher:latest
          echo docker rm switcher || echo not found
          echo docker run --name switcher -b -p 4200:80 victorvsm/angular-themes-switcher:latest
