name: Deploy Angular App
on:
  push:
    branches:
      - 'main'
      - 'prod'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: mode-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint Application
        run: npm run lint
  build:
    needs: lint
    strategy:
      matrix:
        node-versions: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: mode-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Deploy Application
        run: npm run build
      - name: Deploy App
        run: echo Deploying app...
