name: Deploy Angular App
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
  lint:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Lint Application
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Deploy Application
        run: npm run build
      - name: Deploy App
        run: echo Deploying app...

