name: Deploy Angular App
on:
  push:
    branches:
      - 'main'
      - 'prod'
    paths-ignore:
      - '.github/workflows/*'
jobs:
  lint:
    runs-on: self-hosted
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint Application
        run: npm run lint
  build:
    needs: lint
    continue-on-error: true
    strategy:
      matrix:
        node-versions: [14, 16, 18]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Cache dependences
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        run: npm ci
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Get build Project
        uses: actions/download-artifact@v3
        with:
          name: build-files
      - name: Display structure of downloaded files
        run: ls -R
